### PR TITLE
add labels

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
Fixes https://github.com/JuliaTeX/PGFPlots.jl/issues/124.

### CODE REVIEW

**Comment by mykelk** [comment]
Looks like this is generating an error:
```
ERROR: LoadError: LoadError: type Histogram has no field legendentry
Stacktrace:
 [1] getproperty at ./sysimg.jl:18 [inlined]
 [2] plotHelper(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Axis) at /home/travis/build/JuliaTeX/PGFPlots.jl/src/PGFPlots.jl:717
 [3] plot(::Axis) at /home/travis/build/JuliaTeX/PGFPlots.jl/src/PGFPlots.jl:726
 [4] plot at /home/travis/build/JuliaTeX/PGFPlots.jl/src/PGFPlots.jl:764 [inlined]
 [5] #save#45(::Bool, ::Function, ::String, ::PGFPlots.Plots.Histogram) at /home/travis/build/JuliaTeX/PGFPlots.jl/src/PGFPlots.jl:890
```

**Comment by BeastyBlacksmith** [comment]
On second thought, this implementation can break too easily because of the possibly duplicate labels in one document.
I am not quite sure what the best solution would be. Maybe pass the labelnames to the `plot` function via keyword and don't create labels otherwise.

**Comment by mykelk** [comment]
Yeah, that sounds like a better solution.

**Comment by BeastyBlacksmith** [comment]
Changed that. Still, this will not be recognized if used via Plots.jl

**Comment by BeastyBlacksmith** [comment]
which would change, if https://github.com/JuliaPlots/Plots.jl/pulls gets merged.

**Comment by mykelk** [comment]
Should we merge this (after fixing conflicts)?

**Comment by BeastyBlacksmith** [comment]
Good to go :)

**Pull request merged**
